CREATE DATABASE IF NOT EXISTS BD_APLICATIVO_MUSICA;
USE BD_APLICATIVO_MUSICA;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    FOTO BLOB
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(300)
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    FOTO BLOB,
    DATA_LANCAMENTO DATE NOT NULL,
    QTD_MUSICA INTEGER NOT NULL,
    AVALIACAO VARCHAR(300),
    FK_ARTISTA_CPF VARCHAR(14),
    FOREIGN KEY (FK_ARTISTA_CPF) REFERENCES ARTISTA(CPF)
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DURACAO VARCHAR(10) NOT NULL,
    LETRA VARCHAR(1400),
    CAPA BLOB,
    FK_ALBUM_ID INTEGER,
    FK_GENERO_ID INTEGER,
    FOREIGN KEY (FK_ALBUM_ID) REFERENCES ALBUM(ID),
    FOREIGN KEY (FK_GENERO_ID) REFERENCES GENERO(ID)
);