CREATE DATABASE IF NOT EXISTS BD_BIBLIOTECA;
USE BD_BIBLIOTECA;

CREATE TABLE IF NOT EXISTS AUTOR(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    FOTO BLOB,
    QTD_LIVRO INTEGER,
    AVALIACAO VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS LEITOR(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMIAL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS LIVRO_DIGITAL(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL,
    FOTO BLOB NOT NULL,
    AVALIACAO VARCHAR(500),
    FK_CPF_AUTOR VARCHAR(14),
    FOREIGN KEY (FK_CPF_AUTOR) REFERENCES AUTOR(CPF) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LIVRO_ACESSADO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ID_LIVRO_DIGITAL INTEGER,
    FK_CPF_LEITOR VARCHAR(14),
    FOREIGN KEY (FK_ID_LIVRO_DIGITAL) REFERENCES LIVRO_DIGITAL(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_CPF_LEITOR) REFERENCES LEITOR(CPF) ON DELETE CASCADE
);