CREATE DATABASE IF NOT EXISTS BD_CONSULTAS_MEDICAS;
USE BD_CONSULTAS_MEDICAS;

CREATE TABLE IF NOT EXISTS PACIENTE(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS MEDICO(
	CRM INTEGER PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TEELFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONSULTA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA_HORA VARCHAR(20) NOT NULL,
    SENHA VARCHAR(250),
    FK_CPF_PACIENTE VARCHAR(14),
    FK_CRM_MEDICO INTEGER,
    FOREIGN KEY (FK_CPF_PACIENTE) REFERENCES PACIENTE(CPF) ON DELETE CASCADE,
    FOREIGN KEY (FK_CRM_MEDICO) REFERENCES MEDICO(CRM) ON DELETE CASCADE
);