CREATE DATABASE IF NOT EXISTS BD_ENQUETES;
USE BD_ENQUETES;

CREATE TABLE IF NOT EXISTS USUARIO(
	USU_CODIGO INTEGER AUTO_INCREMENT,
    USU_DATA_CADASTRO DATE NOT NULL,
    USU_LOGIN VARCHAR(255) NOT NULL UNIQUE,
    USU_AREA_ATUACAO VARCHAR(500),
    USU_PROFISSAO VARCHAR(200),
    USU_AREA_FORMACAO VARCHAR(500),
    USU_DATANASC DATE NOT NULL,
    USU_ESTADO_CIVIL ENUM("SOLTEIRO", "CASADO", "DIVORCIADO", "VIÚVO") NOT NULL,
    USU_ESTADO VARCHAR(2) NOT NULL,
    USU_ESCOLARIDADE ENUM("FUNDAMENTAL", "MÉDIO", "SUPERIOR") NOT NULL,
    USU_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    USU_SENHA VARCHAR(255) NOT NULL,
    USU_NOME VARCHAR(255) NOT NULL,
    PRIMARY KEY (USU_CODIGO)
);

CREATE TABLE IF NOT EXISTS ENQUETE(
	ENQ_CODIGO INTEGER AUTO_INCREMENT,
    ENQ_DATA_FINAL DATE,
    ENQ_DATA_INICIAL DATE NOT NULL,
    ENQ_DESCRICAO VARCHAR(500) NOT NULL,
    ENQ_NOME VARCHAR(255) NOT NULL,
    FK_USU_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (ENQ_CODIGO),
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO (USU_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USUARIO_RESPONDE_ENQUETE(
	URE_CODIGO INTEGER AUTO_INCREMENT,
    URE_DATA DATE NOT NULL,
    FK_USU_CODIGO INTEGER,
    FK_ENQ_CODIGO INTEGER,
    PRIMARY KEY (URE_CODIGO),
    FOREIGN KEY(FK_USU_CODIGO) REFERENCES USUARIO (USU_CODIGO) ON DELETE CASCADE,
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE (ENQ_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PERGUNTAS(
	PER_CODIGO INTEGER AUTO_INCREMENT,
    PER_DESCRICAO VARCHAR(500) NOT NULL UNIQUE,
    FK_ENQ_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (PER_CODIGO),
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE (ENQ_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESPOSTAS(
	RES_CODIGO INTEGER AUTO_INCREMENT,
    RES_DESCRICAO VARCHAR(500) NOT NULL UNIQUE,
    RES_CERTA VARCHAR(1) NOT NULL,
    FK_PER_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (RES_CODIGO),
    FOREIGN KEY (FK_PER_CODIGO) REFERENCES PERGUNTAS (PER_CODIGO) ON DELETE CASCADE
);
SELECT * FROM USUARIO;
INSERT INTO USUARIO (USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_ATUACAO, USU_PROFISSAO, USU_AREA_FORMACAO, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE, USU_EMAIL, USU_SENHA, USU_NOME)
VALUES("2025-09-24", "LORENA_123", "Tecnologia da Informação", "Desenvolvedor de Software", "Ciência da Computação", "1988-05-04", "CASADO","SP", "SUPERIOR", "lorena@email.com","lorena.123", "Lorena Maria Delfino");

INSERT INTO USUARIO (USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_ATUACAO, USU_PROFISSAO, USU_AREA_FORMACAO, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE, USU_EMAIL, USU_SENHA, USU_NOME)
VALUES("2025-04-14", "LUCAS_123", "Saúde", "Enfermeiro", "Enfermagem", "1987-01-14", "CASADO","SP", "MÉDIO", "lucas@email.com","lucas.123", "Lucas Quaglio");

INSERT INTO USUARIO (USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_ATUACAO, USU_PROFISSAO, USU_AREA_FORMACAO, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE, USU_EMAIL, USU_SENHA, USU_NOME)
VALUES("2025-02-03", "SERENA_123", "Engenharia", "Engenheiro Civil", "Engenharia Civil", "1991-06-25", "SOLTEIRO","SP", "SUPERIOR", "serena@email.com","serena.123", "Serena Francischelli");

SELECT * FROM ENQUETE;
INSERT INTO ENQUETE (ENQ_DATA_FINAL, ENQ_DATA_INICIAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUES("2025-10-11", "2025-10-10", "Sim", "Cor do céu", "1");

INSERT INTO ENQUETE (ENQ_DATA_FINAL, ENQ_DATA_INICIAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUES("2025-09-02", "2025-09-03", "Não", "Cor do morango", "2");

INSERT INTO ENQUETE (ENQ_DATA_FINAL, ENQ_DATA_INICIAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUES("2025-11-21", "2025-11-23", "Sim", "Cor do Limão", "3");

SELECT * FROM USUARIO_RESPONDE_ENQUETE;
INSERT INTO USUARIO_RESPONDE_ENQUETE (URE_DATA, FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES("2025-10-11", "1", "1");

INSERT INTO USUARIO_RESPONDE_ENQUETE (URE_DATA, FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES("2025-09-02", "2", "2");

INSERT INTO USUARIO_RESPONDE_ENQUETE (URE_DATA, FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES("2025-11-21", "3", "3");

SELECT * FROM PERGUNTAS;
INSERT INTO PERGUNTAS (PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES("Qual a cor do céu?", "1");

INSERT INTO PERGUNTAS (PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES("Qual a cor do morango?", "2");

INSERT INTO PERGUNTAS (PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES("Qual a cor do limão?", "3");

SELECT * FROM RESPOSTAS;
INSERT INTO RESPOSTAS (RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES("a - Azul", "a", "1");

INSERT INTO RESPOSTAS (RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES("b - Verde", "a", "1");

INSERT INTO RESPOSTAS (RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES("c - Vermelho", "a", "1");
