CREATE DATABASE IF NOT EXISTS BD_GERENCIAR_PROJETOS;
USE BD_GERENCIAR_PROJETOS;

CREATE TABLE IF NOT EXISTS PROJETO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(500) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    ORCAMENTO DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNVIONARIO(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TAREFA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(500) NOT NULL,
    FK_ID_PROJETO INTEGER,
    FOREIGN KEY (FK_ID_PROJETO) REFERENCES PROJETO(ID)
);

CREATE TABLE IF NOT EXISTS REALIZACAO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ID_TAREFA INTEGER,
    FK_CPF_FUNVIONARIO VARCHAR(14),
    FOREIGN KEY (FK_ID_TAREFA) REFERENCES TAREFA(ID),
    FOREIGN KEY (FK_CPF_FUNVIONARIO) REFERENCES FUNVIONARIO(CPF)
);