CREATE DATABASE IF NOT EXISTS BD_RESERVAS_AEREAS;
USE BD_RESERVAS_AEREAS;

CREATE TABLE IF NOT EXISTS VOO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA_VOO DATE NOT NULL,
    DESCRICAO VARCHAR(500),
    QTD_ASSENTO INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS PASSAGEIRO(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSENTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NUMERO INTEGER NOT NULL,
    DESCRICAO VARCHAR(500),
    VALOR DOUBLE NOT NULL,
    FK_ID_VOO INTEGER,
    FK_CPF_PASSAGEIRO VARCHAR(14),
    FOREIGN KEY (FK_ID_VOO) REFERENCES VOO(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_CPF_PASSAGEIRO) REFERENCES PASSAGEIRO(CPF) ON DELETE CASCADE
);