USE BD_SUPERMERCADO_FUNCIONARIO_PRODUTO_CONSUMIDOR;

INSERT INTO SUPERMERCADO(	SUP_CNPJ,
							SUP_RAZAO_SOCIAL, 
                            SUP_TELEFONE,
                            SUP_EMAIL,
                            SUP_ENDERECO_LOGRADOURO,
                            SUP_ENDERECO_NUMERO,
                            SUP_ENDERECO_CIDADE,
                            SUP_ENDERECO_ESTADO)
VALUES (	"12345678000101",
			"Supermercado Grick",
            "19999999999",
            "gricktambau@email.com",
            "Grick Street",
            "10000",
            "Tambau City",
            "SP");
            
INSERT INTO SUPERMERCADO(	SUP_CNPJ,
							SUP_RAZAO_SOCIAL, 
							SUP_TELEFONE,
							SUP_EMAIL,
							SUP_ENDERECO_LOGRADOURO,
							SUP_ENDERECO_NUMERO,
							SUP_ENDERECO_CIDADE,
							SUP_ENDERECO_ESTADO)
VALUES 					(	'98765432000122',
							'Supermercado Nova Vida',
							"19998887777",
							'contato@novavida.com',
							'Avenida Central',
							'250',
							'Campinas',
							'SP');

INSERT INTO SUPERMERCADO(	SUP_CNPJ,
							SUP_RAZAO_SOCIAL, 
							SUP_TELEFONE,
							SUP_EMAIL,
							SUP_ENDERECO_LOGRADOURO,
							SUP_ENDERECO_NUMERO,
							SUP_ENDERECO_CIDADE,
							SUP_ENDERECO_ESTADO)
VALUES 					(	'11223344000155',
							'Supermercado Bom Preço',
							"19999444999",
							'atendimento@bompreco.com',
							'Rua das Flores',
							'789',
							'Curitiba',
							'PR');

INSERT INTO SUPERMERCADO(	SUP_CNPJ,
							SUP_RAZAO_SOCIAL, 
							SUP_TELEFONE,
							SUP_EMAIL,
							SUP_ENDERECO_LOGRADOURO,
							SUP_ENDERECO_NUMERO,
							SUP_ENDERECO_CIDADE,
							SUP_ENDERECO_ESTADO)
VALUES (
    '5543322000188',
    'Supermercado Estrela',
    "19333999999",
    'contato@estrela.com',
    'Avenida Brasil',
    '1020',
    'Rio de Janeiro',
    'RJ'
);


INSERT INTO SUPERMERCADO(	SUP_CNPJ,
							SUP_RAZAO_SOCIAL, 
							SUP_TELEFONE,
							SUP_EMAIL,
							SUP_ENDERECO_LOGRADOURO,
							SUP_ENDERECO_NUMERO,
							SUP_ENDERECO_CIDADE,
							SUP_ENDERECO_ESTADO)
VALUES (
    '66778899000111',
    'Supermercado Pague Menos',
    "19911199988",
    'suporte@paguemenos.com',
    'Rua das Palmeiras',
    '55',
    'Belo Horizonte',
    'MG'
);

INSERT INTO PRODUTO(	PRO_CODIGO_BARRAS,
						PRO_NOME,
                        PRO_PESO,
                        PRO_QUANTIDADE,
                        PRO_PRECO,
                        PRO_DATA_VALIDADE)
                        
VALUES 				(	"78945632112328",
						"Arroz 5kg",
                        5.0,
                        500,
                        26.90,
                        "2025-12-25");
                        
INSERT INTO PRODUTO(	PRO_CODIGO_BARRAS,
						PRO_NOME,
						PRO_PESO,
						PRO_QUANTIDADE,
						PRO_PRECO,
						PRO_DATA_VALIDADE)
VALUES (
    "78912345678901",
    "Feijão Carioca 1kg",
    1.0,
    300,
    8.50,
    "2025-11-10"
);

INSERT INTO PRODUTO(	PRO_CODIGO_BARRAS,
						PRO_NOME,
						PRO_PESO,
						PRO_QUANTIDADE,
						PRO_PRECO,
						PRO_DATA_VALIDADE)
VALUES 				(	"78998765432109",
						"Macarrão Espaguete 500g",
						0.5,
						400,
						5.90,
						"2026-01-15");

INSERT INTO PRODUTO(	PRO_CODIGO_BARRAS,
						PRO_NOME,
						PRO_PESO,
						PRO_QUANTIDADE,
						PRO_PRECO,
						PRO_DATA_VALIDADE)
VALUES (	"78974185296300",
			"Açúcar Refinado 2kg",
			2.0,
			250,
			7.80,
			"2025-09-30");

INSERT INTO PRODUTO(	PRO_CODIGO_BARRAS,
						PRO_NOME,
						PRO_PESO,
						PRO_QUANTIDADE,
						PRO_PRECO,
						PRO_DATA_VALIDADE)
VALUES (	"78936925814777",
			"Óleo de Soja 900ml",
			0.9,
			350,
			6.20,
			"2025-08-20");

INSERT INTO CONSUMIDOR (	CON_CPF,
							CON_NOME,
                            CON_TELEFONE,
                            CON_EMAIL)
VALUES 					(	"43796038816",
							"Yasmin Francischelli",
                            "19991552501",
                            "yasmin.francischelli@aluno.senai.br");
                            
INSERT INTO FUNCIONARIO (	FUN_CPF,
							FUN_NOME,
                            FUN_DATA_NASC,
                            FUN_TELEFONE,
                            FUN_EMAIL,
                            FUN_CARTEIRA_TRABALHO,
                            FUN_BANCO_AGENCIA,
                            FUN_BANCO_CONTA,
                            FUN_DATA_ADMISSAO,
                            FUN_JORNADA_TRABALHO,
                            FK_SUP_CNPJ)
VALUES 					(	"96325874112",
							 "João da Silva",
							 "1988-09-10",
							 "19996325874",
							 "joao.silva@email.com",
							 "carteira_joao_silva.pdf",
							 "4321",
							 "97745",
							 "2023-11-03",
							 "44 horas",
							 "98765432000122");
                         
INSERT INTO FUNCIONARIO (	FUN_CPF,
							FUN_NOME,
							FUN_DATA_NASC,
							FUN_TELEFONE,
							FUN_EMAIL,
							FUN_CARTEIRA_TRABALHO,
							FUN_BANCO_AGENCIA,
							FUN_BANCO_CONTA,
							FUN_DATA_ADMISSAO,
							FUN_JORNADA_TRABALHO,
							FK_SUP_CNPJ)
VALUES 					(	"74185296300",
							"Maria Fernandes",
							"1992-03-15",
							"11998567412",
							"maria.fernandes@email.com",
							"carteira_maria_fernandes.pdf",
							"1020",
							"56321",
							"2022-08-12",
							"40 horas",
							"98765432000122");

INSERT INTO FUNCIONARIO (	FUN_CPF,
							FUN_NOME,
							FUN_DATA_NASC,
							FUN_TELEFONE,
							FUN_EMAIL,
							FUN_CARTEIRA_TRABALHO,
							FUN_BANCO_AGENCIA,
							FUN_BANCO_CONTA,
							FUN_DATA_ADMISSAO,
							FUN_JORNADA_TRABALHO,
							FK_SUP_CNPJ)
VALUES 					(	"85296314777",
							"Carlos Eduardo",
							"1985-07-20",
							"21987451236",
							"carlos.eduardo@email.com",
							"carteira_carlos_eduardo.pdf",
							"2030",
							"88542",
							"2021-05-03",
							"44 horas",
							"98765432000122");

INSERT INTO FUNCIONARIO (	FUN_CPF,
							FUN_NOME,
							FUN_DATA_NASC,
							FUN_TELEFONE,
							FUN_EMAIL,
							FUN_CARTEIRA_TRABALHO,
							FUN_BANCO_AGENCIA,
							FUN_BANCO_CONTA,
							FUN_DATA_ADMISSAO,
							FUN_JORNADA_TRABALHO,
							FK_SUP_CNPJ)
VALUES 					(	"96374125811",
							"Fernanda Lima",
							"1996-11-28",
							"31996325478",
							"fernanda.lima@email.com",
							"carteira_fernanda_lima.pdf",
							"3105",
							"77889",
							"2024-02-10",
							"36 horas",
							"98765432000122");

INSERT INTO FUNCIONARIO (	FUN_CPF,
							FUN_NOME,
							FUN_DATA_NASC,
							FUN_TELEFONE,
							FUN_EMAIL,
							FUN_CARTEIRA_TRABALHO,
							FUN_BANCO_AGENCIA,
							FUN_BANCO_CONTA,
							FUN_DATA_ADMISSAO,
							FUN_JORNADA_TRABALHO,
							FK_SUP_CNPJ)
VALUES 					(	"15975348622",
							"Rafael Souza",
							"1990-01-05",
							"41991237854",
							"rafael.souza@email.com",
							"carteira_rafael_souza.pdf",
							"4021",
							"33521",
							"2023-06-21",
							"44 horas",
							"98765432000122");
                            
INSERT INTO SUPERMERCADO_PRODUTO (FK_SUP_CNPJ, FK_PRO_ID)
VALUES
('12345678000101', 1),
('12345678000101', 2),
('98765432000122', 3),
('98765432000122', 4),
('11223344000155', 5);

INSERT INTO PRODUTO_CONSUMIDOR (FK_CON_CPF, FK_PRO_ID)
VALUES
('43796038816', 1),
('43796038816', 2),
('43796038816', 3),
('43796038816', 4),
('43796038816', 5);

SELECT * FROM SUPERMERCADO;

/*
CONSULTAR O AUMENTO DE R$ 2,00 NO PREÇO DOS PRODUTOS COM PREÇO ATUAL >= R$5,00
*/
SELECT 	PRO_NOME AS "NOME",
		PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        PRO_PRECO AS "PREÇO ATUAL",
        TRUNCATE((PRO_PRECO + 2),2) AS "PREÇO COM AJUSTE DE R$ 2,00"
FROM 	PRODUTO
WHERE 	PRO_PRECO >= 5;

/*
CONSULTAR A REDUÇÃO DE R$ 1,00 NO PREÇO DOS PRODUTOS COM O PREÇO ATUAL ABAIXO DE R$5,00
*/
SELECT 	PRO_NOME AS "NOME",
		PRO_CODIGO_BARRAS AS "CODIGO DE BARRAS",
        PRO_PRECO AS "PREÇO ATUAL",
        TRUNCATE((PRO_PRECO - 1),2) AS "PREÇO COM REDUÇÃO DE R$1,00"
FROM 	PRODUTO
WHERE	PRO_PRECO <=10;

/*
CONSULTAR COMO SERIA APLICAR UM DESCONTO DE 10% EM TODOS OS PRODUTOS
*/
SELECT	PRO_NOME AS "NOME",
		PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        PRO_PRECO AS "PREÇO ATUAL",
        (PRO_PRECO-(PRO_PRECO * 0.1)) AS "PREÇO COM DESCONTO DE 10%"
FROM 	PRODUTO;
/*AJUSTAR O ESTOQUE DO PRIMEIRO PRODUTO, DIVIDINDO PELA METADE*/
SELECT 	PRO_NOME,
		PRO_CODIGO_BARRAS,
        PRO_ID,
        PRO_QUANTIDADE
FROM 	PRODUTO;

UPDATE 	PRODUTO
SET 	PRO_QUANTIDADE = PRO_QUANTIDADE / 2
WHERE PRO_ID = 1;

/* CONSULTAR TODOS OS PRODUTO QUE TENHAM DATA DE VALIDADE ENTRE SETEMBRO 2025 E DEZEMBRO DE 2025*/

SELECT PRO_NOME AS "NOME",
		PRO_CODIGO_BARRAS AS "CODIGO DE BARRAS",
        PRO_DATA_VALIDADE AS "DATA DE VALIDADE"
FROM    PRODUTO 
WHERE   PRO_DATA_VALIDADE BETWEEN '2025-09-01' AND '2025-12-31';
				

/* CONSULTAR TODOS OS PRODUTOS QUE TENHAM PREÇO MAIOR QUE R$ 10 OU MENOR QUE R$ 4*/
SELECT PRO_NOME AS "NOME",
		PRO_CODIGO_BARRAS AS "CODIGO DE BARRAS", 
        PRO_PRECO AS "PRECO"
FROM    PRODUTO
WHERE   PRO_PRECO  >=10  OR PRO_PRECO <=4;

/* CONSULTAR OS DDDS E TELEFONES DOS CONSUMIDORES SEPARADAMENTE*/
SELECT CON_NOME                     AS "NOME DO CONSUMIDOR",
		CON_CPF                     AS "CPF DO CONSUMIDOR",
        SUBSTRING(CON_TELEFONE,1,2) AS "DDD DO TELEFONE",
        SUBSTRING(CON_TELEFONE,3,9) AS "NUMERO DO TELEFONE"
FROM    CONSUMIDOR;

/*GERAR UMA FRASE CONCATENANDO:
RAZÃO SOCIAL DO SUPERMERCADO, CNPJ, TELEFONE E EMAIL*/
SELECT CONCAT("RAZÃO SOCIAL: ", 
				CONCAT(SUP_RAZAO_SOCIAL, 
						CONCAT(" | CNPJ: ", 
								CONCAT(SUP_CNPJ, 
										CONCAT(" | TELEFONE: ", 
												CONCAT(SUP_TELEFONE, 
														CONCAT(" | EMAIL: ", SUP_EMAIL))))))) AS FRASE
FROM SUPERMERCADO;

/* GERAR UMA CONSULTA QUE VERIFICA O STATUS DO ESTOQUE DOS PRODUTOS
REGRAS:
1) QUANTIDADE <=25: ESTOQUE BAIXO
2) QUANTIDADE > 25 E QUANTIDADE <=100: ESTOQUE MÉDIO
3) QUANTIDADE> 100: ESTOQUE ALTO*/

SELECT PRO_NOME AS "NOME",
		PRO_CODIGO_BARRAS AS "CODIGO DE BARRAS",
        PRO_QUANTIDADE AS "QUANTIDADE",
        CASE
			WHEN PRO_QUANTIDADE <= 25 THEN "ESTOQUE BAIXO"
            WHEN PRO_QUANTIDADE > 25 AND PRO_QUANTIDADE < 100 THEN "ESTOQUE MÉDIO"
            WHEN PRO_QUANTIDADE >= 100 THEN "ESTOQUE ALTO"
		END AS "NÍVEL DE ESTOQUE"
FROM PRODUTO;

/* GERAR UMA CONSULTA QUE VERIFICA O STATUS DO PESO DOS PRODUTOS
retomar: NOME, CODIGO DE BARRAS, QAUNTIDADE, PESO E DATA DE VALIDADE
REGRAS:
1) PESO <=5: PESO BAIXO
2) PESO > 5 E QUANTIDADE <=100: ESTOQUE MÉDIO
3) PESO >= 50: ESTOQUE ALTO*/

SELECT PRO_NOME AS "NOME SO PRODUTO",
		PRO_CODIGO_BARRAS AS "CODIGO DE BARRAS",
        PRO_QUANTIDADE AS "QUANTIDADE",
        PRO_DATA_VALIDADE AS "DATA DE VALIDADE", 
        PRO_PESO AS "PESO DO PRODUTO",
        CASE 
			WHEN PRO_PESO <=5 THEN "PESO BAIXO"
            WHEN PRO_PESO >5 THEN "PESO MÉDIO "
            WHEN PRO_PESO >50 THEN "PESO ALTO"
		END AS "CLASSIFIÇÃO DO PESO"
	FROM PRODUTO;
    
    /* CONTAR QUANTOS CONSUMIDORES TEMOS CADASTRADOS */
    SELECT COUNT(*)
    FROM CONSUMIDOR;

  /* CONTAR QUANTOS SUPERMERCADO TEMOS CADASTRADOS */
    SELECT COUNT(*)
    FROM SUPERMERCADO;

  /* CONTAR QUANTOS FUNCIONARIO TEMOS CADASTRADOS */
    SELECT COUNT(*)
    FROM FUNCIONARIO;

  /* CONTAR QUANTOS PRODUTO TEMOS CADASTRADOS */
    SELECT COUNT(*)
    FROM PRODUTO;

/* somar O PREÇO TOTAL DE TODOS OS PRODUTOS CADASTADOS */
SELECT SUM(PRO_PRECO)
FROM PRODUTO;

SELECT CONCAT("R$", TRUNCATE (SUM(PRO_PRECO),2)) AS "SOMA TOTAL"
FROM PRODUTO;

/* CALCULAR A MEDIA DE PREÇOS DOS PRODUTOS    */
SELECT AVG( PRO_PRECO)
FROM PRODUTO;

SELECT CONCAT("R$", TRUNCATE(AVG(PRO_PRECO),2)) AS "MÉDIA DE PRECO"
FROM PRODUTO;

/* SELECIONAR O PRODUTO MAIS CARO */
SELECT MAX(PRO_PRECO)
FROM PRODUTO;


/* SELECIONAR O ESTOQUE COM MAIOR QUANTIDADE */ 
SELECT MAX(PRO_QUANTIDADE)
FROM PRODUTO;

/* SELECIONAR O PRODUTO MAIS BARATO */
SELECT MIN(PRO_PRECO)
FROM PRODUTO;

/* SELECIONAR O ESTOQUE COM MENOR QUANTIDADE */ 
SELECT MIN(PRO_QUANTIDADE)
FROM PRODUTO;

/* DATA E HORA ATUAL */
SELECT NOW() FROM DUAL;

SELECT FUN_NOME AS "NOME DO FUNCIONARIO ",
	   DATE_FORMAT(FUN_DATA_NASC, "%d / %m / %Y")  AS "DATA DE NASCIMENTO ",
       TIMESTAMPDIFF( YEAR, FUN_DATA_NASC, NOW()) AS "IDADE"
FROM FUNCIONARIO;

/* FUNÇOES MATEMATICAS:
ABS - VALOR ABSOLUTO DEUM NÚMERO
ROUND - ARREDONDAR
POWER - POTÊNCIA  */
SELECT ABS(-10),
	   round(PRO_PRECO) AS "PREÇO ARREDONDADO",
       POWER(PRO_PRECO,2) as "PREÇO ELEVADO AO QUADRADO"
       
FROM PRODUTO;

/* UPPER, LOWER, TRIM */
 SELECT UPPER(FUN_NOME) AS "MAIÚSCULAS",
	    LOWER(FUN_NOME) AS "MINÚCULAS",
        TRIM("LORRANA") AS "TIRANDO ESPEÇOS"
FROM FUNCIONARIO;

SELECT 	PRO_QUANTIDADE,
		COUNT(*) AS "REPETIÇÕES"
FROM  	PRODUTO
GROUP BY PRO_QUANTIDADE;

/* UNION */
SELECT 	FUN_NOME,
		FUN_CPF
FROM 	FUNCIONARIO
UNION
SELECT 	FUN_NOME,
		FUN_CPF
FROM 	FUNCIONARIO;

SELECT * FROM PRODUTO;

/*UNION*/
SELECT 	PRO_NOME
FROM 	PRODUTO
UNION
SELECT 	"Arroz 5kg"
FROM DUAL
UNION
SELECT  "Iogurt do Bob Esponja"
FROM DUAL;

/*UNION ALL*/
SELECT 	PRO_NOME
FROM 	PRODUTO
UNION ALL
SELECT 	"Arroz 5kg"
FROM DUAL
UNION ALL
SELECT  "Iogurt do Bob Esponja"
FROM DUAL;

/* SELECT COM WHERE*/
SELECT 	FUN_NOME 									AS "NOME DO FUNCIONÁRIO",
		FUN_CPF 									AS "CPF DO FUNCIONÁRIO",
		FUN_DATA_NASC 								AS "DATA DE NASCIMENTO",
		TIMESTAMPDIFF(YEAR, FUN_DATA_NASC, NOW())	AS "IDADE"
FROM 	FUNCIONARIO
WHERE 	TIMESTAMPDIFF (YEAR, FUN_DATA_NASC, NOW()) >= 25
AND 	TIMESTAMPDIFF (YEAR, FUN_DATA_NASC, NOW()) <= 35;

/*RETORNAR OS FUNCIONARIOS, CONSUMIDORES E SUPERMERCADOS COM EMAIL IGUAL A HOTMAIL OU OUTLOOK*/
SELECT 	CON_NOME 		AS "NOME",
		CON_CPF			AS "CPF/ CNPJ",
        CON_TELEFONE 	AS "TELEFONE",
        CON_EMAIL 		AS "EMAIL",
        "CONSUMIDOR" 	AS "TIPO"
FROM 	CONSUMIDOR
WHERE	UPPER (CON_EMAIL) LIKE "%EMAIL%"
OR 		UPPER (CON_EMAIL) LIKE "%OUTLOOK%"
UNION
SELECT 	FUN_NOME 		AS "NOME",
		FUN_CPF 		AS "CPF/ CNPJ",
        FUN_TELEFONE 	AS "TELEFONE",
        FUN_EMAIL 		AS "EMAIL",
        "FUNCIONARIO" 	AS "TIPO"
FROM 	FUNCIONARIO
WHERE 	UPPER (FUN_EMAIL) LIKE "%EMAIL%"
OR 		UPPER (FUN_EMAIL) LIKE "%OUTLOOK%"
UNION
SELECT 	SUP_RAZAO_SOCIAL 	AS "NOME",
		SUP_CNPJ 			AS "CPF/ CNPJ",
        SUP_TELEFONE 		AS "TELEFONE",
        SUP_EMAIL 			AS "EMAIL",
        "SUPERMERCADO" 		AS "TIPO"
FROM 	SUPERMERCADO
WHERE	UPPER (SUP_EMAIL) LIKE "%EMAIL%"
OR 		UPPER (SUP_EMAIL) LIKE "%OUTLOOK%";

/* CROSS JOIN: RETORNAR TODOS OS PRODUTOS E OS SUPERMERCADOS EM QUE SÃO VENDIDOS*/
SELECT 	PRODUTO.PRO_NOME 				AS "NOME",
		PRODUTO.PRO_CODIGO_BARRAS 		AS "CODIGO DE BARRAS",
        SUPERMERCADO.SUP_RAZAO_SOCIAL 	AS "RAZÃO SOCIAL"
FROM 	SUPERMERCADO_PRODUTO
CROSS JOIN SUPERMERCADO
CROSS JOIN PRODUTO
WHERE PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID
AND SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ;

/*INNER JOIN: RETORNAR APENAS OS PRODUTOS QUE FORAM COMPRADOS POR ALGUM CONSUMIDOR*/
SELECT 	PRODUTO_CONSUMIDOR.PCO_ID 	AS "ID DA COMPRA",
		PRODUTO.PRO_NOME 			AS "NOME DO PRODUTO",
        PRODUTO.PRO_CODIGO_BARRAS	AS "CODIGO DE BARRAS",
        CONSUMIDOR.CON_NOME 		AS "NOME DO CONSUMIDOR",
        CONSUMIDOR.CON_CPF 			AS "CPF DO CONSUMIDOR"
FROM 	PRODUTO_CONSUMIDOR
INNER JOIN PRODUTO ON (PRODUTO_CONSUMIDOR.FK_PRO_ID = PRODUTO.PRO_ID)
INNER JOIN CONSUMIDOR ON (PRODUTO_CONSUMIDOR.FK_CON_CPF = CONSUMIDOR.CON_CPF);

/*EXERCÍCIO COM INNER JOIN: 
RETORNAR APENAS OS FUNCIONÁRIOS QUE TRABALHAM EM UM SUPERMERCADO
RETORNAR O NOME DO FUNCIONÁRIO E O NOME DO SUPERMERCADO QUE ELE TRABALHA*/
SELECT 	SUPERMERCADO.SUP_RAZAO_SOCIAL 	AS "NOME DO SUPERMERCADO",
		FUNCIONARIO.FUN_NOME 			AS "NOME DO FUNCIONARIO"
FROM 	SUPERMERCADO
INNER JOIN FUNCIONARIO ON (SUPERMERCADO.SUP_CNPJ = FUNCIONARIO.FK_SUP_CNPJ);

/*EXERCÍCIO 2 COM INNER JOIN:
RETORNAR APENAS OS PRODUTOS QUE EXISTAM EM UM SUPERMERCADO
RETORNAR O NOME DO PRODUTO E O NOME DO SUPERMERCADO QUE ELE ESTÁ DISPONÍVEL*/
SELECT 	SUPERMERCADO.SUP_RAZAO_SOCIAL AS "CNPJ DO MERCADO",
		PRODUTO.PRO_NOME AS "ID DO PRODUTO"
FROM 	SUPERMERCADO_PRODUTO
INNER JOIN SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ)
INNER JOIN PRODUTO ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID);

/*LEFT JOIN*/
INSERT INTO PRODUTO		(PRO_CODIGO_BARRAS,
						PRO_NOME,
                        PRO_PESO,
                        PRO_QUANTIDADE,
                        PRO_PRECO,
                        PRO_DATA_VALIDADE)
VALUE 					("3333333333",
						"KitKat",
                        "30",
                        "1500",
                        "4.50",
                        "2026-01-01");
                        
SELECT 	PRODUTO.PRO_NOME,
		SUPERMERCADO.SUP_RAZAO_SOCIAL
FROM 	PRODUTO
LEFT JOIN SUPERMERCADO_PRODUTO ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID)
LEFT JOIN SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ);

SELECT * FROM SUPERMERCADO;

SELECT 	PRODUTO.PRO_NOME,
		SUPERMERCADO.SUP_RAZAO_SOCIAL
FROM 	PRODUTO
RIGHT JOIN SUPERMERCADO_PRODUTO ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID)
RIGHT JOIN SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ);

/*SELECT COM LEFT JOIN E RIGHT JOIN*/
SELECT 	*
FROM 	(
			SELECT S.SUP_RAZAO_SOCIAL 	AS RAZAO_SOCIAL,
					F.FUN_NOME 			AS NOME_FUNCIONARIO,
                    P.PRO_NOME 			AS NOME_PRODUTO,
                    C.CON_NOME 			AS NOME_CONSUMIDOR
			FROM 	SUPERMERCADO S
            LEFT JOIN FUNCIONARIO F 			ON (S.SUP_CNPJ = F.FK_SUP_CNPJ)
            LEFT JOIN SUPERMERCADO_PRODUTO SP	ON (S.SUP_CNPJ = SP.FK_SUP_CNPJ)
            LEFT JOIN PRODUTO P 				ON (SP.FK_PRO_ID = P.PRO_ID)
            LEFT JOIN PRODUTO_CONSUMIDOR PC 	ON (P.PRO_ID = PC.FK_PRO_ID)
            LEFT JOIN CONSUMIDOR C				ON (PC.FK_CON_CPF = C.CON_CPF)
            UNION
            SELECT S.SUP_RAZAO_SOCIAL 	AS RAZAO_SOCIAL,
					F.FUN_NOME 			AS NOME_FUNCIONARIO,
                    P.PRO_NOME 			AS NOME_PRODUTO,
                    C.CON_NOME 			AS NOME_CONSUMIDOR
			FROM 	SUPERMERCADO S
            RIGHT JOIN FUNCIONARIO F 			ON (S.SUP_CNPJ = F.FK_SUP_CNPJ)
            RIGHT JOIN SUPERMERCADO_PRODUTO SP	ON (S.SUP_CNPJ = SP.FK_SUP_CNPJ)
            RIGHT JOIN PRODUTO P 				ON (SP.FK_PRO_ID = P.PRO_ID)
            RIGHT JOIN PRODUTO_CONSUMIDOR PC 	ON (P.PRO_ID = PC.FK_PRO_ID)
            RIGHT JOIN CONSUMIDOR C				ON (PC.FK_CON_CPF = C.CON_CPF)
            
) SELECT_EXTERNO
ORDER BY 	SELECT_EXTERNO.RAZAO_SOCIAL 	ASC,
			SELECT_EXTERNO.NOME_FUNCIONARIO DESC,
            SELECT_EXTERNO.NOME_PRODUTO 	ASC,
            SELECT_EXTERNO.NOME_CONSUMIDOR 	DESC;
            
/*1- LISTE O NOME DO SUPERMERCADO E O NOME DOS PRODUTOS QUE ELE VENDE*/
SELECT 	PRODUTO.PRO_NOME 				AS "NOME",
        SUPERMERCADO.SUP_RAZAO_SOCIAL 	AS "RAZÃO SOCIAL"
FROM 	SUPERMERCADO_PRODUTO
INNER JOIN  PRODUTO ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID)
INNER JOIN SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ);

/*2- MOSTRE O NOME DE FUNCIONARIO E O NOME DO SUPERMERCADO QUE ELE TRABALHA*/
SELECT 	SUPERMERCADO.SUP_RAZAO_SOCIAL 	AS "NOME DO SUPERMERCADO",
		FUNCIONARIO.FUN_NOME 			AS "NOME DO FUNCIONARIO"
FROM 	SUPERMERCADO
INNER JOIN FUNCIONARIO ON (SUPERMERCADO.SUP_CNPJ = FUNCIONARIO.FK_SUP_CNPJ);

/*3- EXIBA O NOME DO CONSUMIDOR E O NOME DOS PRODUTOS QUE ELE COMPROU*/
SELECT 	CONSUMIDOR.CON_NOME 		AS "NOME DO CONSUMIDOR",
		PRODUTO.PRO_NOME 			AS "NOME DO PRODUTO"
FROM 	PRODUTO_CONSUMIDOR
INNER JOIN CONSUMIDOR ON (PRODUTO_CONSUMIDOR.FK_CON_CPF = CONSUMIDOR.CON_CPF)
INNER JOIN PRODUTO ON (PRODUTO_CONSUMIDOR.FK_PRO_ID = PRODUTO.PRO_ID);

/*4- LISTE OS NOMES DOS PRODUTOS E OS RESPECTIVOS CONSUMIDORES QUE OS COMPRARAM*/
SELECT 	PRODUTO.PRO_NOME 			AS "NOME DO PRODUTO",
        CONSUMIDOR.CON_NOME 		AS "NOME DO CONSUMIDOR"
FROM 	PRODUTO_CONSUMIDOR
INNER JOIN PRODUTO ON (PRODUTO_CONSUMIDOR.FK_PRO_ID = PRODUTO.PRO_ID)
INNER JOIN CONSUMIDOR ON (PRODUTO_CONSUMIDOR.FK_CON_CPF = CONSUMIDOR.CON_CPF);

/*5- MOSTRE O NOME DO SUPERMERCADO E A QUNTIDADE TOTAL DE PRODUTOS CADASTRADOS POR ELE*/
SELECT 	COUNT( PRODUTO.PRO_QUANTIDADE) AS "PRODUTOS CADASTRADOS",
		SUPERMERCADO.SUP_RAZAO_SOCIAL AS "NOME DO SUPERMERCADO"
FROM 	SUPERMERCADO_PRODUTO
INNER JOIN PRODUTO ON (SUPERMERCADO_PRODUTO.FK_PRO_ID = PRODUTO.PRO_ID)
INNER JOIN SUPERMERCADO ON (SUPERMERCADO_PRODUTO.FK_SUP_CNPJ = SUPERMERCADO.SUP_CNPJ)
GROUP BY SUPERMERCADO.SUP_RAZAO_SOCIAL;

/*EXERCÍCIOS LEFT JOIN*/

/*1- LISTE TODOS OS SUPERMERCADOS, MOSTRANDO TAMBÉM SEUS PRODUTOS - MESMO QUE ALGUM SUPERMERCADO NÃO TENHA PRODUTOS*/
SELECT 	SUPERMERCADO.SUP_RAZAO_SOCIAL,
		PRODUTO.PRO_NOME
FROM 	SUPERMERCADO
LEFT JOIN SUPERMERCADO_PRODUTO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ)
LEFT JOIN PRODUTO ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID);

/*2- MOSTRE TODOS OS FUNCIONÁRIOS E O NOME DE SUPERMERCADO - INCLUINDO FUNCIONÁRIOS QUE AINDA NÃO ESTÃO VINCULADOS*/
SELECT	FUNCIONARIO.FUN_NOME,
		SUPERMERCADO.SUP_RAZAO_SOCIAL
FROM	FUNCIONARIO
LEFT JOIN SUPERMERCADO ON (FUNCIONARIO.FK_SUP_CNPJ = SUPERMERCADO.SUP_CNPJ);

/*3- EXIBA TODOSMOS CONSUMIDORES E OS PRODUTOS QUE ELES COMPRARAM  - INCLUINDO CONSUMIDORES QUE AINDA NÃO REALIZARAM COMPRAS*/
SELECT 	CONSUMIDOR.CON_NOME,
		PRODUTO.PRO_NOME
FROM 	CONSUMIDOR
LEFT JOIN PRODUTO_CONSUMIDOR ON (CONSUMIDOR.CON_CPF = PRODUTO_CONSUMIDOR.FK_CON_CPF)
LEFT JOIN PRODUTO ON (PRODUTO.PRO_ID = PRODUTO_CONSUMIDOR.FK_PRO_ID);

/*4- LISTE TODOS OS PRODUTOS E OS CONSUMIDORES QUE OS COMPRARAM - MESMO QUE UM PRODUTO AINDA NÃO TENHA SIDO COMPRADO*/
SELECT 	PRODUTO.PRO_NOME,
		CONSUMIDOR.CON_NOME
FROM 	PRODUTO
LEFT JOIN PRODUTO_CONSUMIDOR ON (PRODUTO.PRO_ID = PRODUTO_CONSUMIDOR.FK_PRO_ID)
LEFT JOIN CONSUMIDOR ON (CONSUMIDOR.CON_CPF = PRODUTO_CONSUMIDOR.FK_CON_CPF);

/*5- */
SELECT	SUPERMERCADO.SUP_RAZAO_SOCIAL,
		FUNCIONARIO.FUN_NOME
FROM	SUPERMERCADO
LEFT JOIN FUNCIONARIO ON (FUNCIONARIO.FK_SUP_CNPJ = SUPERMERCADO.SUP_CNPJ);

/*EXERCÍCIOS RIGHT JOIN*/

/*1- LISTE OS PRODUTOS E OS SUPERMERCADOS QUE OS VENDEM - INCLUINDO PRODUTOS QUE AINDA NÃO PERTENCEM A NENHUM SUPERMERCADO*/
SELECT 	SUPERMERCADO.SUP_RAZAO_SOCIAL,
		PRODUTO.PRO_NOME
FROM 	SUPERMERCADO
RIGHT JOIN SUPERMERCADO_PRODUTO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ)
RIGHT JOIN PRODUTO ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID);

/*2- MOSTRE TODOS OS CONSUMIDORES E OS PRODUTOS QUE COMPRARAM - INCLUINDO PRODUTOS QUE AINDA NÃO FORAM COMPRADOS*/
SELECT 	CONSUMIDOR.CON_NOME,
		PRODUTO.PRO_NOME
FROM 	CONSUMIDOR
RIGHT JOIN PRODUTO_CONSUMIDOR ON (CONSUMIDOR.CON_CPF = PRODUTO_CONSUMIDOR.FK_CON_CPF)
RIGHT JOIN PRODUTO ON (PRODUTO.PRO_ID = PRODUTO_CONSUMIDOR.FK_PRO_ID);

/*3- EXIBA TODOS OS FUNCIONÁRIOS E OS SUPERMERCADOS - INCLUINDO SUPERMERCADOS QUE AINDA NÃO POSSUEM FUNCIONÁRIOS*/
SELECT	FUNCIONARIO.FUN_NOME,
		SUPERMERCADO.SUP_RAZAO_SOCIAL
FROM	FUNCIONARIO
RIGHT JOIN SUPERMERCADO ON (FUNCIONARIO.FK_SUP_CNPJ = SUPERMERCADO.SUP_CNPJ);

/*4- LISTE TODOS OS SUPERMERCADOS E OS PRODUTOS - INCLUINDO OS PRODUTOS QUE AINDA NÃO ESTÃO ASSOCIADOS A NENHUM SUPERMERCADO*/
SELECT 	SUPERMERCADO.SUP_RAZAO_SOCIAL,
		PRODUTO.PRO_NOME
FROM 	SUPERMERCADO
RIGHT JOIN SUPERMERCADO_PRODUTO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ)
RIGHT JOIN PRODUTO ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID);

/*5- MOSTRE TODOS OS CONSUMIDORES E PRODUTOS - MOSMO QUE ALGUM PRODUTO NÃO TENHA SIDO COMPRADO*/
SELECT 	CONSUMIDOR.CON_NOME,
		PRODUTO.PRO_NOME
FROM 	CONSUMIDOR
RIGHT JOIN PRODUTO_CONSUMIDOR ON (CONSUMIDOR.CON_CPF = PRODUTO_CONSUMIDOR.FK_CON_CPF)
RIGHT JOIN PRODUTO ON (PRODUTO.PRO_ID = PRODUTO_CONSUMIDOR.FK_PRO_ID);

/*SELECIONAR APENAS OS PRODUTOS QUE POSSUEM REGISTRO EM UM SUPERMERCADO E QUE FORAM COMPRADOS POR UM CONSUMIDOR*/
SELECT	P.PRO_NOME AS "NOME DO PRODUTO",
		P.PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        P.PRO_PRECO AS "PREÇO DO PRODUTO"
FROM PRODUTO P 
WHERE	P.PRO_ID IN		(SELECT SP.FK_PRO_ID FROM SUPERMERCADO_PRODUTO SP)
AND 	P.PRO_ID IN 	(SELECT PC.FK_PRO_ID FROM PRODUTO_CONSUMIDOR PC);

/*SELECIONAR APENAS OS PRODUTOS QUE NÃO POSSUEM REGISTRO EM UM SUPERMERCADO E QUE NÃO FORAM COMPRADOS POR UM CONSUMIDOR*/
SELECT	P.PRO_NOME AS "NOME DO PRODUTO",
		P.PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        P.PRO_PRECO AS "PREÇO DO PRODUTO"
FROM PRODUTO P 
WHERE	P.PRO_ID NOT IN		(SELECT SP.FK_PRO_ID FROM SUPERMERCADO_PRODUTO SP)
AND 	P.PRO_ID NOT IN 	(SELECT PC.FK_PRO_ID FROM PRODUTO_CONSUMIDOR PC);